task:
    name: AddressSanitizer C++ (Clang 21, Ubuntu 25.10)
    skip: "changesIncludeOnly('contrib/*', 'contrib/**/*', 'doc/*', 'doc/**/*', 'docker/remote-testing/*', 'docker/remote-testing/**/*', 'po/*', 'po/**/*', 'snap/*', 'snap/**/*')"

    container:
      greedy: true
      dockerfile: docker/ubuntu_25.10-build-tools.dockerfile
      docker_arguments:
          # We need llvm-symbolizer from llvm-21-tools to demangle symbols in
          # sanitizer's reports. ASAN library is in libclang-rt-dev
          cxx_package: "clang-21 llvm-21 libclang-rt-21-dev"
          cc: clang-21
          cxx: clang++-21

    env:
      CXXFLAGS: "-fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -fno-optimize-sibling-calls -g"
      ASAN_OPTIONS: "check_initialization_order=1:detect_stack_use_after_return=1"
      JOBS: 8

    cargo_cache: &cargo_cache
        # This works in conjunction with after_cache_script and
        # before_cache_script defined below.
        folder: $HOME/cargo-cache
        fingerprint_script:
          # We include the cache name in the fingerprint to avoid re-using old
          # caches that contained ~/.cargo
          - echo cargo-cache
          - cat Cargo.lock

    # Sanitizers only apply to C++, so we only build and run C++ tests. Also,
    # we don't pass --keep-going to the build: failures can be debugged with
    # logs of other jobs.
    after_cache_script: &after_cache_script
      - mkdir $HOME/.cargo || true
      - mv $HOME/cargo-cache/registry/ $HOME/cargo-cache/git/ $HOME/.cargo/ || true
    build_script: make -j${JOBS} test
    test_script: cd test && ./test --order=rand --rng-seed=time
    before_cache_script: &before_cache_script
        # Cirrus CI sometimes fails to unpack the cache. In that case, it
        # removes the "cache folder" and tries again.
        #
        # We used to use ~/.cargo as a "cache folder", but Cirrus then
        # sometimes removed ~/.cargo/bin and broke the build. To work around
        # that, we're storing the cacheble stuff in a separate directory which
        # we move in/out of ~/.cargo before/after the build.
        - mkdir -p $HOME/cargo-cache/git/
        - mv $HOME/.cargo/registry/ $HOME/cargo-cache/ || true
        - mv $HOME/.cargo/git/db/ $HOME/cargo-cache/git/ || true

task:
    name: AddressSanitizer Rust (Clang 21, Ubuntu 25.10)
    skip: "changesIncludeOnly('contrib/*', 'contrib/**/*', 'doc/*', 'doc/**/*', 'docker/remote-testing/*', 'docker/remote-testing/**/*', 'po/*', 'po/**/*', 'snap/*', 'snap/**/*')"

    container:
      greedy: true
      dockerfile: docker/ubuntu_25.10-build-tools.dockerfile
      docker_arguments:
          # We need llvm-symbolizer from llvm-21-tools to demangle symbols in
          # sanitizer's reports. ASAN library is in libclang-rt-dev
          cxx_package: "clang-21 llvm-21 libclang-rt-21-dev"
          cc: clang-21
          cxx: clang++-21

    env:
      RUSTFLAGS: "-Zsanitizer=address"
      RUSTDOCFLAGS: "-Zsanitizer=address"
      LSAN_OPTIONS: "report_objects=1"
      JOBS: 8

    cargo_cache: *cargo_cache

    after_cache_script: *after_cache_script
    setup_llvm_symbolizer_script: "ln -s $(which llvm-symbolizer-18) /home/builder/.cargo/bin/llvm-symbolizer"
    cargo_test_with_asan: "cargo +nightly test --target x86_64-unknown-linux-gnu"
    before_cache_script: *before_cache_script

task:
    name: UB Sanitizer (Clang 21, Ubuntu 25.10)
    skip: "changesIncludeOnly('contrib/*', 'contrib/**/*', 'doc/*', 'doc/**/*', 'docker/remote-testing/*', 'docker/remote-testing/**/*', 'po/*', 'po/**/*', 'snap/*', 'snap/**/*')"

    container:
      greedy: true
      dockerfile: docker/ubuntu_25.10-build-tools.dockerfile
      docker_arguments:
          # We need llvm-symbolizer from llvm-21-tools to demangle symbols in
          # sanitizer's reports. UB sanitizer library is in libclang-rt-dev
          cxx_package: "clang-21 llvm-21 libclang-rt-21-dev"
          cc: clang-21
          cxx: clang++-21

    env:
      CXXFLAGS: "-fsanitize=undefined -g -fno-omit-frame-pointer"
      UBSAN_OPTIONS: "suppressions=.undefined-sanitizer-suppressions:print_stacktrace=1:halt_on_error=1"
      JOBS: 8

    cargo_cache: *cargo_cache

    # Sanitizers only apply to C++, so we only build and run C++ tests. Also,
    # we don't pass --keep-going to the build: failures can be debugged with
    # logs of other jobs.
    after_cache_script: *after_cache_script
    build_script: make -j${JOBS} test
    test_script: cd test && ./test --order=rand --rng-seed=time
    before_cache_script: *before_cache_script
