[workspace]
members = [
    "rust/libnewsboat",
    "rust/libnewsboat-ffi",
    "rust/strprintf",
    "rust/regex-rs",
    "rust/http-test-server",
]
resolver = "2"

[workspace.lints.clippy]
assigning_clones = "allow"
