CXXFLAGS+=-fprofile-arcs -ftest-coverage
CFLAGS+=-fprofile-arcs -ftest-coverage
LCOV_FILE=newsbeuter.info
OUTDIR?=.


include Makefile

lcov-init:
	$(RM) $(LCOV_FILE)

lcov-add:
	lcov -b . -d . -c --output-file $(LCOV_FILE)

lcov-html:
	genhtml -o $(OUTDIR) $(LCOV_FILE)
