[package]
name = "http-test-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httpmock = "0.7.0"

[lints]
workspace = true
