A podcast is a media file distributed over the internet using syndication feeds
such as RSS, for later playback on portable players or computers.
Newsboat supports downloading, saving and streaming podcasts, though an external
media player is needed for playback. This support differs a bit from other
podcast aggregators or "podcatchers" in how it is done.

Podcast content is transported in RSS feeds via special tags called
"enclosures". Newsboat recognizes these enclosures and stores the relevant
information for every podcast item it finds in an RSS feed. Since version 2.0,
it also recognizes and handles the Yahoo Media RSS extensions.

The following sections present two different ways to handle podcasts with
newsboat.

==== Managing Audio Files with Podboat

What the user can do is to add the podcast download URL to a download queue.
Alternatively, newsboat can be configured to automatically do that. This
queue is stored in the _queue_ file next to the _cache.db_ file.

The user can then use the download manager `podboat` to download these files
to a directory on the local filesystem. Podboat comes with the newsboat
package, and features a look and feel very close to the one of newsboat. It
also shares the same configuration file.

Podcasts that have been downloaded but haven't been played yet remain in the
queue but are marked as downloaded. You can remove them by purging them from
the queue with the "P" key. After you've played a file and close podboat, it
will be removed from the queue. The downloaded file remains on the
filesystem unless "delete-played-files" is enabled.

A common "use case" is to configure newsboat to automatically enqueue newly
found podcast download URLs. Then, the user reloads the podcast RSS feeds in
newsboat, and after that, uses podboat to view the current queue, and
either selectively download certain files or automatically download them all
together by pressing "a" within podboat.

