= NEWSBOAT(1)
Alexander Batischev <eual.jp@gmail.com>


== NAME

newsboat - an RSS/Atom feed reader for text terminals


== SYNOPSIS

*newsboat* [*-r*] [*-e*] [*-i* _opmlfile_] [*-u* _urlfile_] [*-c* _cachefile_] [*-C* _configfile_] [*-X*] [*-o*] [*-x* _command_...] [*-h*]


== DESCRIPTION

_Newsboat_ is an RSS/Atom feed reader for text terminals. RSS and Atom are a
number of widely-used XML formats to transmit, publish and syndicate articles,
for example news or blog articles.  Newsboat is designed to be used on text
terminals on Unix or Unix-like systems such as GNU/Linux, BSD or macOS.


== OPTIONS

*-h*, *--help*::
        Display help

*-r*, *--refresh-on-start*::
        Refresh feeds on start

*-e*, *--export-to-opml*::
        Export feeds as OPML to stdout. This currently outputs OPML 1.0, losing
        all tag information, but this is subject to change to 2.0 in the future.

*--export-to-opml2*::
        Export feeds as OPML 2.0, including tags, to stdout

*-X*, *--vacuum*::
        Compact the cache by: 1) reclaiming the space that was left empty when
        data was deleted; and 2) defragmenting the entries in the cache. This
        *doesn't* delete the entries; for that, see _cleanup-on-quit_,
        _delete-read-articles-on-quit_, _keep-articles-days_, and _max-items_
        settings.

*--cleanup*::
        Remove unreferenced entries from the cache and quit Newsboat. Feeds and
        their articles will be removed if the feedurl is no longer in the
        _urls_ file.
+
Additionally, if the _delete-read-articles-on-quit_ configuration is set, all
read articles will be deleted (including articles of feeds which are still in
the _urls_ file).

*-v*, *-V*, *--version*::
        Get version information about Newsboat and the libraries it uses

*-i* _opmlfile_, *--import-from-opml*=_opmlfile_::
       Import an OPML file

*-u* _urlfile_, *--url-file*=_urlfile_::
       Use an alternative URL file

*-c* _cachefile_, *--cache-file*=_cachefile_::
       Use an alternative cache file

*-C* _configfile_, *--config-file*=_configfile_::
       Use an alternative configuration file

*--queue-file*=_queuefile_::
       Use an alternative queue file

*--search-history-file*=_searchhistoryfile_::
       Use an alternative search history file

*--cmdline-history-file*=_cmdlinehistoryfile_::
       Use an alternative command line history file

*-x* _command_ ..., *--execute*=_command_...::
       Execute one or more commands to run Newsboat unattended. Currently available
       commands are _reload_ and _print-unread_.

*-l* _loglevel_, *--log-level*=_loglevel_::
       Generate a logfile with a certain _loglevel_ (valid values: 1 to 6, for user error,
       critical, error, warning, info, and debug respectively).
       Filename can be specified using the *--log-file* option. If not specified,
       a filename is generated of the form newsboat_<date-time>.log

*-d* _logfile_, *--log-file*=_logfile_::
       Use this _logfile_ as output when logging debug messages. Please note that this
       only works when providing a loglevel.

*-E* _file_, *--export-to-file*=_file_::
       Export a list of read articles (resp. their GUIDs). This can be used to
       transfer information about read articles between different computers.

*-I* _file_, *--import-from-file*=_file_::
      Import a list of read articles and mark them as read if they are held in the
      cache. This is to be used in conjunction with the *-E* commandline parameter.

== FIRST STEPS

include::chapter-firststeps.asciidoc[]

== CONFIGURATION

include::chapter-configuration.asciidoc[]

== CONFIGURATION COMMANDS

include::newsboat-cfgcmds.asciidoc[]

== AVAILABLE OPERATIONS

include::newsboat-keycmds.asciidoc[]

== FORMAT STRINGS

include::chapter-format-strings.asciidoc[]

== TAGGING

include::chapter-tagging.asciidoc[]

== SCRIPTS AND FILTERS

include::chapter-snownews.asciidoc[]

== KILLFILES

include::chapter-killfiles.asciidoc[]

== PODCAST SUPPORT

include::chapter-podcasts.asciidoc[]

== COMMAND LINE

include::chapter-cmdline.asciidoc[]

_quit_::
        Quit Newsboat
_q_::
        Alias for _quit_

_save_ <filename>::
        Save current article to <filename>

[[cmd-set]] _set_ <variable>[=<value>|&|!]::
        Set (or get) configuration variable value. Specifying a _!_ after the name of a boolean configuration variable toggles their values, a _&_ directly after the name of a configuration variable of any type resets its value to the documented default value.

_tag_ <tagname>::
        Select a certain tag

_goto_ <case-insensitive substring>::
        Go to the next feed whose name contains the case-insensitive substring.

_source_ <filename> [...]::
        Load the specified configuration files. This allows it to load alternative configuration files or reload already loaded configuration files on-the-fly from the filesystem.

_dumpconfig_ <filename>::
       Save current internal state of configuration to file, so that it can be instantly reused as configuration file.

_<number>_::
        Jump to the <number>th entry in the current dialog


== FILES

include::chapter-files.asciidoc[]

dotfiles::
        _~/.newsboat/config_
+
_~/.newsboat/urls_

XDG::
        _$XDG_CONFIG_HOME/newsboat/config_
+
_$XDG_CONFIG_HOME/newsboat/urls_
+
Note: if the `XDG_CONFIG_HOME` environment variable is not set, Newsboat behaves as if it was set to _~/.config_.


== ENVIRONMENT

include::chapter-environment-variables.asciidoc[]

== SEE ALSO

podboat(1)
