Podboat(1)
===========
Alexander Batischev <eual.jp@gmail.com>


NAME
----
podboat - a podcast download manager for text terminals


SYNOPSIS
--------
'podboat' [-C configfile] [-q queuefile] [-a] [-h]


DESCRIPTION
-----------
'podboat' is a podcast manager for text terminals. It is a helper program to
'newsboat' which queues podcast downloads into a file. These queued downloads
can then be download with 'newsboat'.


OPTIONS
-------
-h, --help::
        Display help

-C configfile, --config-file=configfile::
       Use an alternative configuration file

-q queuefile, --queue-file=queuefile::
       Use an alternative queue file

-a, --autodownload::
       Start automatic download of all queued files on startup

-l loglevel, --log-level=loglevel::
       Generate a logfile with a certain loglevel. Valid loglevels are 1 to 6. An
       actual logfile will only be written when you provide a logfile name.

-d logfile, --log-file=logfile::
       Use this logfile as output when logging debug messages. Please note that this
       only works when providing a loglevel.

PODCAST SUPPORT
---------------

include::chapter-podcasts.asciidoc[]


CONFIGURATION COMMANDS
----------------------

include::podboat-cfgcmds.asciidoc[]


XDG Base Directory Support
--------------------------

Podboat defaults to storing everything in '$HOME/.newsboat' directory. If
you prefer XDG, create '$HOME/.config/newsboat' and
'$HOME/.local/share/newsboat' directories, and Podboat will use them from
there on.

If you already have some files in '$HOME/.newsboat/', move the 'queue' file to
'$HOME/.local/share/newsboat/', and that should be it.

See also a corresponding section in newsboat(1).


FILES
-----

dotfiles::
        '$HOME/.newsboat/config'
        +
        '$HOME/.newsboat/queue'

XDG::
        '$HOME/.config/newsboat/config'
        +
        '$HOME/.local/share/newsboat/queue'


ENVIRONMENT
-----------

include::chapter-environment-variables.asciidoc[]


SEE ALSO
--------
newsboat(1)
