.\" (c) 2006 Andreas Krennmair <ak@synflood.at>
.\" run groff -T ps -man newsbeuter.1 > manpage.ps to generate nice PostScript output
.Dd Dec 20, 2006
.Dt NB-PLANET 1
.Os "nb-planet"
.Sh NAME
.Nm nb-planet
.Nd a "planet"-like RSS feed aggregator
.Sh SYNOPSIS
.Nm nb-planet
.Op Fl u Ar urlfile
.Op Fl c Ar cachefile
.Op Fl C Ar configfile
.Op Fl v
.Op Fl h
.Sh DESCRIPTION
.Nm
is an RSS feed aggregator similar to "planet" and built on top of the
newsbeuter components.
.Sh OPTIONS
.Nm
accepts the following commandline switches:
.Bl -tag
.It Fl h
Display help
.It Fl v
Make program output more verbose
.It Fl u Ar urlfile
Use an alternative URL file
.It Fl c Ar cachefile
Use an alternative cache file
.It Fl C Ar configfile
Use an alternative configuration file
.El
.Sh FILES
.Bl -item
.It
.Pa $HOME/.newsbeuter/config
.It
.Pa $HOME/.newsbeuter/urls
.El
.Sh SEE ALSO
.Xr newsbeuter 1 ,
.Xr podbeuter 1

The documentation that comes with newsbeuter is a good source about the general use and
configuration of nb-planet.
.Sh AUTHORS
.Bd -literal
.An Andreas Krennmair <ak@synflood.at>, for contributors see AUTHORS file.
.Ed
