.\" (c) 2007 Andreas Krennmair <ak@synflood.at>
.\" run groff -T ps -man newsbeuter.1 > manpage.ps to generate nice PostScript output
.Dd Feb 25, 2007
.Dt PODBEUTER 1
.Os "podbeuter"
.Sh NAME
.Nm podbeuter
.Nd a podcast download manager for text terminals
.Sh SYNOPSIS
.Nm podbeuter
.Op Fl C Ar configfile
.Op Fl q Ar queuefile
.Op Fl h
.Sh DESCRIPTION
.Nm
is a podcast download manager for text terminals. It is a helper program to 
.Nm newsbeuter
which queues podcast downloads into a file. These queued downloads can then
be downloaded with
.Nm .
.Sh OPTIONS
.Nm
accepts the following commandline switches:
.Bl -tag
.It Fl h
Display help
.It Fl C Ar configfile
Use an alternative configuration file
.It Fl q Ar queuefile
Use an alternative queue file
.El
.Sh FILES
.Bl -item
.It
.Pa $HOME/.newsbeuter/config
.It
.Pa $HOME/.newsbeuter/queue
.El
.Sh SEE ALSO
.Xr newsbeuter 1

The documentation that comes with newsbeuter is a good source about the general use and
configuration of newsbeuter's podcast support.
.Sh AUTHORS
.Bd -literal
.An Andreas Krennmair <ak@synflood.at>, for contributors see AUTHORS file.
.Ed
