name: "No dbg! macros in Rust code"

on:
  push:
  pull_request:

jobs:
  changes:
    name: "Detect relevant changes"
    runs-on: ubuntu-24.04
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v7

      - name: Filter paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            relevant:
              - '**.rs'
              - '.github/**'

  check_for_dbg_macros:
    name: "No dbg! macros in Rust code"
    needs: changes
    if: needs.changes.outputs.relevant == 'true'
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v7

      - name: "Check for dbg! macros"
        # `!` in front of the command negates its exit code: this script will
        # exit with 0 if no matches were found, and with 1 if there are matches.
        # We need parentheses to prevent YAML parser from eating up the
        # exclamation mark.
        run: ( ! grep --extended-regexp --recursive --line-number '\<dbg!' * )
